parserOptions:
  ecmaVersion: 9

plugins:
  - bem-xjst

env:
  browser: true
  node: true
  es6: true
  bem-xjst/bemhtml: true
  bem-xjst/bemtree: true

rules:
  curly: [error, multi-line]
  no-unused-expressions: off

extends: pedant

presets:
  - es2015