import Head from 'next/head'

import styles from './index.module.css';

export default function Error404() {
  return (
    <div>
      <Head>
        <title>Страница не найдена</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-m.ico" />
      </Head>
      <main className={styles.content}>
        <div className={styles.title}><b>404</b> | Такой страницы не существует</div>
        <a className={styles.link} href="/">Вернуться на главную</a>
      </main>
    </div>
  )
}
