({
    shouldDeps: [
        {
            block: 'field',
            elems: [
                'client',
                'contact',
                'city',
                'street',
                'adds',
                'service',
                'add-info',
                'income-once',
                'income-monthly',
                'cs-gzp-pre',
                'date-gzp-pre',
                'cs-gzp-active',
                'date-init',
                'date-gzp-active',
                'date-gzp-build',
                'gzp-need',
                'gzp-add-info',
                'init-file',
                'order',
                'date-sign',
                'cs-stop-pre',
                'date-stop-pre',
                'cs-stop-organization',
                'date-stop-organization',
                'date-stop-build',
                'tech',
                'stop-reason',
                'provider',
                'provider-contact',
                'devices',
                'add-devices',
                'interfaces',
                'time',
                'stop-add-info',
                'stop-org-info',
                'stop-cost-once',
                'stop-cost-monthly',
                'idoss',
                'type-adress',
                'coordinate'
            ]
        }
    ]
})
